@baseUrl = http://localhost:5000/tags

### Create a new tag
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Sports",
  "description": "Football, Basketball, and more"
}

### Get all tags
GET {{baseUrl}}

### Get active tags
GET {{baseUrl}}/active

### Get popular tags
GET {{baseUrl}}/popular?limit=5

### Get tag by ID
GET {{baseUrl}}/682657a8ff7e68e4cfa4bb35

### Update tag
PUT {{baseUrl}}/682657a8ff7e68e4cfa4bb35
Content-Type: application/json

{
  "name": "Tech News",
  "description": "Latest technology news and updates",
  "isActive": true
}

### Delete tag
DELETE {{baseUrl}}/682657a8ff7e68e4cfa4bb35 