services:
  api-server:
    image: api-server
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongodb
    networks:
      - defy-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/mongodb:/data/db 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Sieretech$254
    networks:
      - defy-network
    restart: always

networks:
  defy-network:
    driver: bridge
