@baseUrl = http://localhost:5000/sponsors

### Create a new sponsor
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Nation Media Group",
  "description": "Leading media group",
  "logo": "https://example.com/nation-media-group-logo.png",
  "website": "https://nationmedia.com",
  "contactEmail": "contact@nationmedia.com",
  "contactPhone": "+254712345678",
  "address": "Kimathi Street, Nairobi, Kenya"
}

### Get all sponsors
GET {{baseUrl}}

### Get active sponsors
GET {{baseUrl}}/active

### Get sponsor by ID
GET {{baseUrl}}/65f1a2b3c4d5e6f7g8h9i0j1

### Update sponsor
PUT {{baseUrl}}/682672a0998ea46021d87519
Content-Type: application/json

{
  "description": "Premier technology solutions provider in East Africa",
  "contactPhone": "+254798765432",
  "logo": "https://pbs.twimg.com/profile_images/1230818600820334593/g0JXP_6o_400x400.jpg",
  "address": "456 Innovation Avenue, Nairobi, Kenya"
}

### Delete sponsor
DELETE {{baseUrl}}/65f1a2b3c4d5e6f7g8h9i0j1 