@baseUrl = http://localhost:5000/content/68265b47e01334e4187802d3/comments

### Create a new comment
POST {{baseUrl}}
Content-Type: application/json

{
  "content": "68265b47e01334e4187802d3",
  "text": "This is a great article!"
}

### Get all comments
GET {{baseUrl}}

### Get comments by content ID
GET {{baseUrl}}/content/68265b47e01334e4187802d3

### Get comments by user ID
GET {{baseUrl}}/user/userId

### Get comment by ID
GET {{baseUrl}}/commentId

### Update comment
PUT {{baseUrl}}/commentId
Content-Type: application/json

{
  "text": "Updated comment text"
}

### Delete comment
DELETE {{baseUrl}}/commentId 