name: Deploy Node.js Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          timeout: 30s
          script: |
            # Clone or pull latest backend code
            cd ~/newstribe || git clone git@github.com:Alidantech/newstribe.git && cd newstribe
            git pull origin main

            # Stop and remove any existing backend container
            sudo docker stop newstribe || true
            sudo docker rm newstribe || true

            # Build and run backend container
            sudo docker build -t newstribe .
            sudo docker run -d --name newstribe -p 5000:5000 newstribe